/**
 * Generated-from-OpenAPI types plus ergonomic aliases.
 * `schema.ts` is regenerated by `pnpm --filter @gh-stories/contracts generate`
 * and must not be edited by hand.
 */
export type { paths, components, operations } from './schema.js';
import type { components } from './schema.js';

type S = components['schemas'];

export type ApiError = S['Error'];
export type HealthStatus = S['HealthStatus'];
export type Visibility = S['Visibility'];
export type Emoji = S['Emoji'];
export type PublicUser = S['PublicUser'];
export type Me = S['Me'];
export type SessionInfo = S['SessionInfo'];
export type PendingLogin = S['PendingLogin'];
export type PendingLoginPoll = S['PendingLoginPoll'];
export type ImportSummary = S['ImportSummary'];
export type MediaVariant = S['MediaVariant'];
export type StoryItem = S['StoryItem'];
export type AuthorGroup = S['AuthorGroup'];
export type Feed = S['Feed'];
export type RingStatus = S['RingStatus'];
export type UploadIntent = S['UploadIntent'];
export type UploadIntentRequest = S['UploadIntentRequest'];
export type StoryUpdate = S['StoryUpdate'];
export type ViewerList = S['ViewerList'];
export type Reaction = S['Reaction'];
export type Reply = S['Reply'];
export type InboxEntry = S['InboxEntry'];
export type Inbox = S['Inbox'];
export type Relationship = S['Relationship'];
export type RelationshipPage = S['RelationshipPage'];
export type AudienceList = S['AudienceList'];
export type Settings = S['Settings'];
export type SettingsUpdate = S['SettingsUpdate'];
export type ReportRequest = S['ReportRequest'];
export type Report = S['Report'];

/** The five reactions, in display order. */
export const REACTIONS: readonly Emoji[] = ['❤️', '😂', '🔥', '😭', '💀'] as const;

/** Plain-language audience labels. Shown before publication, never jargon. */
export const VISIBILITY_LABELS: Record<NonNullable<Visibility>, string> = {
  followers_of_author: 'People I follow',
  author_follows: 'My followers',
  mutuals: 'Mutuals',
  custom_list: 'Custom list',
  public: 'Public — anyone signed in',
};

export const VISIBILITY_DESCRIPTIONS: Record<NonNullable<Visibility>, string> = {
  followers_of_author: 'Only people you follow on Stories can see this.',
  author_follows: 'Only people who follow you on Stories can see this.',
  mutuals: 'Only people you follow who also follow you back can see this.',
  custom_list: 'Only the people on the list you choose can see this.',
  public: 'Anyone signed in to GitHub Stories can see this.',
};

/** How long every item stays visible, from the moment it is published. */
export const STORY_LIFETIME_MS = 24 * 60 * 60 * 1000;
