/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Process is alive */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthStatus"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe (database and object storage reachable) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ready */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthStatus"];
                    };
                };
                /** @description Not ready */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthStatus"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/github/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Begin GitHub OAuth (state + PKCE S256 held server side) */
        get: {
            parameters: {
                query?: {
                    /** @description Relative path to return to after login */
                    return_to?: string;
                    /** @description Present when approving a CLI login */
                    pending_login_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to github.com/login/oauth/authorize */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/github/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OAuth redirect target; exchanges the code server side */
        get: {
            parameters: {
                query: {
                    code: string;
                    state: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect into the account application */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/cli/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a pending client authorization for a service-mediated login */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        client_kind: "cli" | "browser_extension";
                        /** @description Human label shown on the approval screen, e.g. 'gh stories on allies-mbp' */
                        client_label?: string;
                    };
                };
            };
            responses: {
                /** @description Pending authorization created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PendingLogin"];
                    };
                };
                429: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/cli/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Poll a pending authorization (bounded, rate limited, single use) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        pending_login_id: string;
                        polling_secret: string;
                    };
                };
            };
            responses: {
                /** @description Current authorization state; token present exactly once on approval */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PendingLoginPoll"];
                    };
                };
                404: components["responses"]["Error"];
                429: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/device/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a GitHub Device Authorization Grant login */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        client_kind: "cli" | "browser_extension";
                        /** @description Human label shown in the session list, e.g. 'gh stories on allies-mbp' */
                        client_label?: string;
                    };
                };
            };
            responses: {
                /** @description Device authorization created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeviceLogin"];
                    };
                };
                429: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/device/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Poll a device authorization (bounded, rate limited, single use) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        device_login_id: string;
                    };
                };
            };
            responses: {
                /** @description Current authorization state; token present exactly once on approval */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeviceLoginPoll"];
                    };
                };
                404: components["responses"]["Error"];
                429: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the calling session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session revoked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's active Stories sessions */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sessions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            sessions?: components["schemas"]["SessionInfo"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke one of the caller's sessions */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Revoked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["Error"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The authenticated Stories account */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current account */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
                401: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding/import-follows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import the people the caller follows on GitHub (opt-out, first login)
         * @description Never mutates GitHub's follow graph. Deduplicates by numeric GitHub id,
         *     preserves relationships to people who have not joined, and never
         *     resurrects a relationship the user explicitly unfollowed.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @default true */
                        enabled?: boolean;
                        /**
                         * @description Compute the change set without applying it
                         * @default false
                         */
                        preview?: boolean;
                    };
                };
            };
            responses: {
                /** @description Import summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportSummary"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Authorized Story feed, grouped by author
         * @description Ordering is deterministic: unseen authors first, then natively followed
         *     authors before import-only authors, then most recent eligible
         *     publication, tie-broken by GitHub user id. Muted authors are omitted.
         *     Fetching the feed never records a view.
         */
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    limit?: number;
                    include_muted?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Feed page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Feed"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Batch ring status for avatars visible on a page
         * @description Reveals only Stories the caller is allowed to access. An inaccessible
         *     active Story and no Story are indistinguishable in this response: both
         *     return `has_active: false` with no counts, timestamps or audiences.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        github_user_ids?: number[];
                        logins?: string[];
                    };
                };
            };
            responses: {
                /** @description Ring states */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            entries?: components["schemas"]["RingStatus"][];
                        };
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find a Stories account by username */
        get: {
            parameters: {
                query: {
                    q: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Matches */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            users?: components["schemas"]["PublicUser"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{login}/stories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A single author's active, authorized Story sequence */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    login: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Author sequence */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthorGroup"];
                    };
                };
                /** @description No account, or nothing this caller may see */
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request an upload authorization for one server-chosen private object key */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Retrying a mutation with the same key returns the original result. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UploadIntentRequest"];
                };
            };
            responses: {
                /** @description Upload authorized */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadIntent"];
                    };
                };
                413: components["responses"]["Error"];
                415: components["responses"]["Error"];
                429: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{uploadId}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize an upload; freezes an immutable worker input and queues processing */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Retrying a mutation with the same key returns the original result. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    uploadId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: int64 */
                        byte_size: number;
                        checksum_sha256: string;
                    };
                };
            };
            responses: {
                /** @description Accepted for processing. This is NOT yet "Story posted". */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StoryItem"];
                    };
                };
                404: components["responses"]["Error"];
                /** @description Replay or already finalized */
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{storyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read one Story item
         * @description Signed-in callers resolve through the full audience predicate; anonymous
         *     callers may read a live public Story only. Anything else is 404.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    storyId: components["parameters"]["StoryId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Story item */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StoryItem"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        /** Delete a Story (immediate loss of server access, physical cleanup scheduled) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    storyId: components["parameters"]["StoryId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["Error"];
            };
        };
        options?: never;
        head?: never;
        /**
         * Update caption, description, audience or interaction settings (author only)
         * @description Narrowing the audience also revokes newly unauthorized media requests.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    storyId: components["parameters"]["StoryId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["StoryUpdate"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StoryItem"];
                    };
                };
                403: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        trace?: never;
    };
    "/stories/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's own active items */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Own items */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthorGroup"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{storyId}/viewers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Named viewer list (author only) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    storyId: components["parameters"]["StoryId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Viewers */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ViewerList"];
                    };
                };
                403: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{storyId}/view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Acknowledge that delivered media actually rendered
         * @description A view is recorded by the media authorization gateway when content-bearing
         *     media is delivered to an authorized non-owner. This endpoint records the
         *     client's separate rendering acknowledgement; it never creates a view for
         *     an unauthorized caller. Anonymous callers may acknowledge a live public
         *     Story; it is a no-op 204 that stores nothing.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    storyId: components["parameters"]["StoryId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Acknowledged */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{storyId}/reaction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set or replace the caller's reaction */
        put: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Retrying a mutation with the same key returns the original result. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    storyId: components["parameters"]["StoryId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        emoji: components["schemas"]["Emoji"];
                    };
                };
            };
            responses: {
                /** @description Reaction stored */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Reaction"];
                    };
                };
                /** @description Reactions disabled for this item */
                403: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        post?: never;
        /** Remove the caller's reaction */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    storyId: components["parameters"]["StoryId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{storyId}/replies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a private reply to the Story's author */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Retrying a mutation with the same key returns the original result. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    storyId: components["parameters"]["StoryId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        body: string;
                    };
                };
            };
            responses: {
                /** @description Reply sent */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Reply"];
                    };
                };
                /** @description Replies disabled */
                403: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Private inbox — replies, reactions and new followers */
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Inbox page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Inbox"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inbox/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark inbox entries read */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        event_ids?: string[];
                        /** @default false */
                        all?: boolean;
                    };
                };
            };
            responses: {
                /** @description Marked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{storyId}/{variant}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Authorization gateway for media (public Stories readable anonymously)
         * @description Checks session, audience, block, hide, suspension, deletion and expiry on
         *     every request including thumbnails and video range requests. Supports
         *     HTTP range. Delivering content-bearing media to an authorized non-owner
         *     records a view. Anonymous callers may fetch a live public Story's media;
         *     it is served with short public caching and increments an aggregate
         *     anonymous counter only — no per-viewer row, no IP history. There are no
         *     public or long-lived object URLs.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    storyId: components["parameters"]["StoryId"];
                    variant: "image" | "video" | "poster" | "thumb" | "terminal";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Media bytes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": string;
                    };
                };
                /** @description Partial content */
                206: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Error"];
                /** @description Not found */
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/following": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Accounts the caller follows on Stories */
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Following */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RelationshipPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/following/{login}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Follow on Stories (never mutates the GitHub follow graph) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    login: components["parameters"]["Login"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Following */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Relationship"];
                    };
                };
                /** @description Blocked */
                403: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        post?: never;
        /** Unfollow (tombstoned so re-import will not resurrect it) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    login: components["parameters"]["Login"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unfollowed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/followers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Accounts following the caller on Stories */
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Followers */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RelationshipPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mutes/{login}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Mute (affects only the muting user's presentation, not access) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    login: components["parameters"]["Login"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Muted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["Error"];
            };
        };
        post?: never;
        /** Unmute */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    login: components["parameters"]["Login"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unmuted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blocks/{login}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Block (overrides audience access in both directions) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    login: components["parameters"]["Login"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Blocked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["Error"];
            };
        };
        post?: never;
        /** Unblock */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    login: components["parameters"]["Login"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unblocked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hides/{login}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Hide my Stories from this person */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    login: components["parameters"]["Login"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Hidden */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["Error"];
            };
        };
        post?: never;
        /** Stop hiding */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    login: components["parameters"]["Login"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unhidden */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mutes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List muted accounts */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Muted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RelationshipPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List blocked accounts */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Blocked */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RelationshipPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List accounts hidden from the caller's Stories */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Hidden */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RelationshipPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audience-lists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Custom audience lists */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lists */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            lists?: components["schemas"]["AudienceList"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a custom audience list */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        logins?: string[];
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AudienceList"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audience-lists/{listId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a list */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    listId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Rename a list or replace its members */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    listId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name?: string;
                        logins?: string[];
                    };
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AudienceList"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Account settings */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Settings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Settings"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update account settings */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SettingsUpdate"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Settings"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/settings/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete the caller's Stories account and all their content */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report a Story or a user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReportRequest"];
                };
            };
            responses: {
                /** @description Report filed */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Report"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moderation/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Moderation queue (moderators only; deny by default) */
        get: {
            parameters: {
                query?: {
                    state?: "open" | "actioned" | "dismissed";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Queue */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            reports?: components["schemas"]["Report"][];
                        };
                    };
                };
                403: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moderation/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Take a moderation action (moderators only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        kind: "remove_story" | "suspend_user" | "unsuspend_user" | "dismiss_report";
                        /** Format: uuid */
                        report_id?: string;
                        /** Format: uuid */
                        story_id?: string;
                        login?: string;
                        reason?: string;
                    };
                };
            };
            responses: {
                /** @description Action recorded */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /** @description Stable machine-readable code, e.g. not_found, forbidden, rate_limited, unsupported_media */
                code: string;
                message: string;
                field?: string;
                retry_after_seconds?: number;
            };
        };
        HealthStatus: {
            /** @enum {string} */
            status?: "ok" | "degraded" | "down";
            version?: string;
            commit?: string;
            checks?: {
                [key: string]: string;
            };
            media_jobs_backlog?: number;
            oldest_media_job_age_seconds?: number;
            cleanup_backlog?: number;
        };
        /**
         * @description followers_of_author — People I follow (signed-in users the author follows)
         *     author_follows      — My followers (signed-in users who follow the author)
         *     mutuals             — Mutuals
         *     custom_list         — Custom list
         *     public              — Public, anyone, no sign-in required
         * @enum {string}
         */
        Visibility: "followers_of_author" | "author_follows" | "mutuals" | "custom_list" | "public";
        /** @enum {string} */
        Emoji: "❤️" | "😂" | "🔥" | "😭" | "💀";
        PublicUser: {
            /** Format: int64 */
            github_user_id: number;
            login: string;
            avatar_url: string;
            profile_url: string;
            /** @description Whether this identity has an active Stories account */
            has_account: boolean;
        };
        Me: {
            user: components["schemas"]["PublicUser"];
            needs_onboarding: boolean;
            is_moderator?: boolean;
            unread_inbox?: number;
            /**
             * Format: date-time
             * @description Authoritative server time
             */
            server_time?: string;
        };
        SessionInfo: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            client_kind?: "browser_extension" | "cli" | "web";
            client_label?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            last_used_at?: string;
            /** Format: date-time */
            expires_at?: string;
            current?: boolean;
        };
        PendingLogin: {
            /** Format: uuid */
            pending_login_id: string;
            /** @description Unguessable; sent only to the requesting client */
            polling_secret: string;
            /** @description Short code the user matches on the approval screen */
            user_code: string;
            /** @description Public URL the user opens to approve */
            verification_url: string;
            /** Format: date-time */
            expires_at: string;
            interval_seconds: number;
        };
        PendingLoginPoll: {
            /** @enum {string} */
            status: "pending" | "approved" | "denied" | "expired";
            /** @description Present exactly once */
            token?: string;
            /** Format: date-time */
            expires_at?: string;
            user?: components["schemas"]["PublicUser"];
        };
        DeviceLogin: {
            /** Format: uuid */
            device_login_id: string;
            /** @description Short code the user matches on github.com */
            user_code: string;
            /** @description GitHub URL the user opens to authorize */
            verification_uri: string;
            /** Format: date-time */
            expires_at: string;
            interval_seconds: number;
        };
        DeviceLoginPoll: {
            /** @enum {string} */
            status: "pending" | "slow_down" | "approved" | "denied" | "expired";
            /** @description Present exactly once */
            token?: string;
            user?: components["schemas"]["PublicUser"];
        };
        ImportSummary: {
            enabled?: boolean;
            preview?: boolean;
            account?: components["schemas"]["PublicUser"];
            github_following_count?: number;
            added?: number;
            already_following?: number;
            /** @description Previously unfollowed on Stories; deliberately not resurrected */
            skipped_unfollowed?: number;
            skipped_blocked?: number;
            sample?: components["schemas"]["PublicUser"][];
        };
        MediaVariant: {
            /** @enum {string} */
            kind: "image" | "video" | "poster" | "thumb" | "terminal";
            /** @description Relative authorization-gateway path; never a public object URL */
            url: string;
            mime: string;
            width?: number;
            height?: number;
            duration_ms?: number;
            /** Format: int64 */
            byte_size?: number;
            has_audio?: boolean;
        };
        StoryItem: {
            /** Format: uuid */
            id: string;
            author: components["schemas"]["PublicUser"];
            /** @enum {string} */
            state: "processing" | "published" | "failed" | "deleted" | "removed";
            caption?: string;
            /** @description Author-supplied accessibility description */
            alt_text?: string;
            visibility?: components["schemas"]["Visibility"];
            /** Format: uuid */
            audience_list_id?: string;
            /** @description Plain-language audience */
            audience_label?: string;
            allow_replies?: boolean;
            allow_reactions?: boolean;
            /** @enum {string} */
            media_kind?: "image" | "video";
            variants?: components["schemas"]["MediaVariant"][];
            /** Format: date-time */
            published_at?: string;
            /**
             * Format: date-time
             * @description Exactly published_at + 24h in server time
             */
            expires_at?: string;
            /** @description Whether the caller has already viewed this item */
            seen?: boolean;
            is_owner?: boolean;
            /** @description Author only */
            viewer_count?: number;
            /** @description Author only */
            reaction_count?: number;
            my_reaction?: components["schemas"]["Emoji"];
            failure_code?: string;
            failure_message?: string;
        };
        AuthorGroup: {
            author: components["schemas"]["PublicUser"];
            items: components["schemas"]["StoryItem"][];
            has_unseen?: boolean;
            muted?: boolean;
            /** @enum {string} */
            follow_provenance?: "github_import" | "stories_native" | "self";
        };
        Feed: {
            me?: components["schemas"]["AuthorGroup"];
            groups: components["schemas"]["AuthorGroup"][];
            next_cursor?: string;
            /** Format: date-time */
            server_time: string;
            /** @description Opaque change token for cheap polling */
            version?: string;
        };
        RingStatus: {
            /** Format: int64 */
            github_user_id: number;
            login?: string;
            /** @description False both for "no Story" and "not authorized" — deliberately indistinguishable */
            has_active: boolean;
            has_unseen?: boolean;
            muted?: boolean;
            is_self?: boolean;
        };
        UploadIntentRequest: {
            /** @description Declared type; the server verifies the real signature during processing */
            mime: string;
            /** Format: int64 */
            byte_size: number;
            /** @description Advisory only; never used to build an object key or a shell argument */
            filename?: string;
            caption?: string;
            alt_text?: string;
            visibility?: components["schemas"]["Visibility"];
            /** Format: uuid */
            audience_list_id?: string;
            allow_replies?: boolean;
            allow_reactions?: boolean;
        };
        UploadIntent: {
            /** Format: uuid */
            upload_id: string;
            /** @enum {string} */
            method: "PUT";
            /** @description Short-lived authorization for exactly one server-chosen private object key */
            url: string;
            headers?: {
                [key: string]: string;
            };
            /** Format: date-time */
            expires_at: string;
            /** Format: int64 */
            max_bytes: number;
        };
        StoryUpdate: {
            caption?: string;
            alt_text?: string;
            visibility?: components["schemas"]["Visibility"];
            /** Format: uuid */
            audience_list_id?: string;
            allow_replies?: boolean;
            allow_reactions?: boolean;
        };
        ViewerList: {
            /** Format: uuid */
            story_id?: string;
            total?: number;
            viewers?: {
                user?: components["schemas"]["PublicUser"];
                /** Format: date-time */
                viewed_at?: string;
                reaction?: components["schemas"]["Emoji"];
            }[];
        };
        Reaction: {
            /** Format: uuid */
            story_id?: string;
            emoji?: components["schemas"]["Emoji"];
            /** Format: date-time */
            created_at?: string;
        };
        Reply: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            story_id?: string;
            sender?: components["schemas"]["PublicUser"];
            recipient?: components["schemas"]["PublicUser"];
            body?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            read_at?: string;
            /** @description Context replaced with "Story expired"; no media is retained */
            story_expired?: boolean;
        };
        InboxEntry: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            kind?: "reply" | "reaction" | "follow";
            actor?: components["schemas"]["PublicUser"];
            /** Format: uuid */
            story_id?: string;
            story_expired?: boolean;
            /** @description Authorization-gateway path; absent once the Story expired */
            story_thumb_url?: string;
            body?: string;
            emoji?: components["schemas"]["Emoji"];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            read_at?: string;
            outgoing?: boolean;
        };
        Inbox: {
            entries?: components["schemas"]["InboxEntry"][];
            unread?: number;
            next_cursor?: string;
        };
        Relationship: {
            user?: components["schemas"]["PublicUser"];
            /** @enum {string} */
            provenance?: "github_import" | "stories_native";
            /** Format: date-time */
            created_at?: string;
            follows_me?: boolean;
            muted?: boolean;
            blocked?: boolean;
            hidden?: boolean;
        };
        RelationshipPage: {
            relationships?: components["schemas"]["Relationship"][];
            next_cursor?: string;
            total?: number;
        };
        AudienceList: {
            /** Format: uuid */
            id?: string;
            name?: string;
            members?: components["schemas"]["PublicUser"][];
            member_count?: number;
        };
        Settings: {
            default_visibility?: components["schemas"]["Visibility"];
            /** Format: uuid */
            default_audience_list_id?: string;
            default_allow_replies?: boolean;
            default_allow_reactions?: boolean;
            audience_lists?: components["schemas"]["AudienceList"][];
            hidden_from?: components["schemas"]["PublicUser"][];
            muted?: components["schemas"]["PublicUser"][];
            blocked?: components["schemas"]["PublicUser"][];
            sessions?: components["schemas"]["SessionInfo"][];
            reply_retention_days?: number;
        };
        SettingsUpdate: {
            default_visibility?: components["schemas"]["Visibility"];
            /** Format: uuid */
            default_audience_list_id?: string;
            default_allow_replies?: boolean;
            default_allow_reactions?: boolean;
        };
        ReportRequest: {
            /** @enum {string} */
            subject_kind: "story" | "user";
            /** Format: uuid */
            story_id?: string;
            login?: string;
            /** @enum {string} */
            reason: "spam" | "harassment" | "nudity" | "violence" | "self_harm" | "illegal" | "other";
            details?: string;
        };
        Report: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            subject_kind?: "story" | "user";
            /** Format: uuid */
            story_id?: string;
            subject?: components["schemas"]["PublicUser"];
            reporter?: components["schemas"]["PublicUser"];
            reason?: string;
            details?: string;
            /** @enum {string} */
            state?: "open" | "actioned" | "dismissed";
            /** Format: date-time */
            created_at?: string;
        };
    };
    responses: {
        /** @description Structured error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        StoryId: string;
        Login: string;
        /** @description Retrying a mutation with the same key returns the original result. */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
